version: "3.8"

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=euller
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis-json:
      image: redislabs/rejson:latest
      container_name: redis-json
      ports:
        - 6379:6379







